services:
  postgres:
    image: postgres:16
    container_name: pizzaria-db
    environment:
      POSTGRES_DB: pizzaria
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"